version: '3.1'
services:
  postgres:
    image: postgres:16
    ports:
      - "25432:5432"
    environment:
      - POSTGRES_USER=civilwar
      - POSTGRES_PASSWORD=civilwar
      - POSTGRES_DB=civilwar
